// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

SEXP unique2(SEXP x);

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("SEXP(*unique2)(SEXP)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(RcppAlgorithms_RcppExports) {
    Rcpp::function("unique2", &unique2, Rcpp::List::create(Rcpp::Named("x")));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
